# Generated by Django 3.2.11 on 2022-01-11 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('titulo', models.CharField(max_length=70)),
                ('editora', models.CharField(blank=True, max_length=70, null=True)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('resenha', models.TextField(blank=True, null=True)),
                ('cod_user', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
