# Generated by Django 3.2.11 on 2022-01-11 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='cod_user',
            new_name='cod_book',
        ),
    ]
